In [1]:
import numpy as np
from scipy.linalg.blas import dsyrk, dgemm

In [2]:
a = np.array(range(5))
b = np.array([10, 20, 30])
c = np.zeros((5, 5))
d = np.zeros((3, 5))

In [12]:
dsyrk(a=a, c=c.T, alpha=1.0, beta=1.0, overwrite_c = True)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  5., 10., 15., 20.],
       [ 0.,  0., 20., 30., 40.],
       [ 0.,  0.,  0., 45., 60.],
       [ 0.,  0.,  0.,  0., 80.]])

In [10]:
dgemm(a=a, b=b, c=d.T, trans_b=True, alpha=1.0, beta=1.0, overwrite_c=True)

array([[  0.,   0.,   0.],
       [ 40.,  80., 120.],
       [ 80., 160., 240.],
       [120., 240., 360.],
       [160., 320., 480.]])

In [13]:
d

array([[  0.,  40.,  80., 120., 160.],
       [  0.,  80., 160., 240., 320.],
       [  0., 120., 240., 360., 480.]])

In [14]:
c + np.tril(c, -1).T

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  5., 10., 15., 20.],
       [ 0., 10., 20., 30., 40.],
       [ 0., 15., 30., 45., 60.],
       [ 0., 20., 40., 60., 80.]])

In [7]:
np.tril(c, -1)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.],
       [ 0.,  3.,  6.,  0.,  0.],
       [ 0.,  4.,  8., 12.,  0.]])